-- MySQL Script generated by MySQL Workbench
-- Sun Nov 26 22:02:40 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema car-stand
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema car-stand
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `car-stand` DEFAULT CHARACTER SET utf8 ;
USE `car-stand` ;

-- -----------------------------------------------------
-- Table `car-stand`.`tb_person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car-stand`.`tb_person` (
  `id_person` INT NOT NULL AUTO_INCREMENT,
  `gender` ENUM('Male', 'Female') NOT NULL DEFAULT 'Male',
  `role` ENUM('Manager', 'Worker') NOT NULL DEFAULT 'Manager',
  `marital_status` ENUM('Single', 'Married', 'Divorced', 'Widower') NOT NULL DEFAULT 'Single',
  `nif` VARCHAR(20) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_person`),
  UNIQUE INDEX `nif_UNIQUE` (`nif` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car-stand`.`tb_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car-stand`.`tb_user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `id_person` INT NOT NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_tb_user_tb_person1_idx` (`id_person` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  CONSTRAINT `fk_tb_user_tb_person`
    FOREIGN KEY (`id_person`)
    REFERENCES `car-stand`.`tb_person` (`id_person`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car-stand`.`tb_brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car-stand`.`tb_brand` (
  `id_brand` INT NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(50) NOT NULL,
  `foundation_year` YEAR NOT NULL,
  `country_of_origin` VARCHAR(50) NOT NULL,
  `headquarters` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_brand`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car-stand`.`tb_model`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car-stand`.`tb_model` (
  `id_model` INT NOT NULL AUTO_INCREMENT,
  `model` VARCHAR(50) NOT NULL,
  `launch_year` YEAR NOT NULL,
  `engine_type` ENUM('Gasoline', 'Diesel', 'Hybrid', 'Electric', 'Natural Gas', 'Ethanol', 'Hydrogen', 'LPG (Liquefied Petroleum Gas)', 'Biodiesel') NOT NULL DEFAULT 'Gasoline',
  PRIMARY KEY (`id_model`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car-stand`.`tb_brand_model`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car-stand`.`tb_brand_model` (
  `id_brand_model` INT NOT NULL AUTO_INCREMENT,
  `tb_brand_id_brand` INT NOT NULL,
  `tb_model_id_model` INT NOT NULL,
  PRIMARY KEY (`id_brand_model`, `tb_brand_id_brand`, `tb_model_id_model`),
  INDEX `fk_tb_brand_has_tb_model_tb_model1_idx` (`tb_model_id_model` ASC),
  INDEX `fk_tb_brand_has_tb_model_tb_brand1_idx` (`tb_brand_id_brand` ASC),
  CONSTRAINT `fk_tb_brand_has_tb_model_tb_brand`
    FOREIGN KEY (`tb_brand_id_brand`)
    REFERENCES `car-stand`.`tb_brand` (`id_brand`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tb_brand_has_tb_model_tb_model`
    FOREIGN KEY (`tb_model_id_model`)
    REFERENCES `car-stand`.`tb_model` (`id_model`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car-stand`.`tb_car`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car-stand`.`tb_car` (
  `id_car` INT NOT NULL AUTO_INCREMENT,
  `color` VARCHAR(50) NOT NULL,
  `chassi` VARCHAR(30) NOT NULL,
  `price` VARCHAR(50) NOT NULL,
  `mileage` VARCHAR(50) NOT NULL,
  `status` ENUM('Available', 'Sold') NOT NULL DEFAULT 'Available',
  `id_brand_model` INT NOT NULL,
  PRIMARY KEY (`id_car`, `id_brand_model`),
  UNIQUE INDEX `chassi_UNIQUE` (`chassi` ASC),
  INDEX `fk_tb_car_tb_brand_model1_idx` (`id_brand_model` ASC),
  CONSTRAINT `fk_tb_car_tb_brand_model`
    FOREIGN KEY (`id_brand_model`)
    REFERENCES `car-stand`.`tb_brand_model` (`id_brand_model`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
